//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 10:51:44 PM CET 
//


package vakcinac.io.citizen.models.sag;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the vakcinac.io.citizen.models.sag package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: vakcinac.io.citizen.models.sag
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SaglasnostZaSprovodjenjePreporuceneImunizacije }
     * 
     */
    public SaglasnostZaSprovodjenjePreporuceneImunizacije createSaglasnostZaSprovodjenjePreporuceneImunizacije() {
        return new SaglasnostZaSprovodjenjePreporuceneImunizacije();
    }

    /**
     * Create an instance of {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji }
     * 
     */
    public SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji createSaglasnostZaSprovodjenjePreporuceneImunizacijeEvidencijaOVakcinaciji() {
        return new SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji();
    }

    /**
     * Create an instance of {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji.Obrazac }
     * 
     */
    public SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji.Obrazac createSaglasnostZaSprovodjenjePreporuceneImunizacijeEvidencijaOVakcinacijiObrazac() {
        return new SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji.Obrazac();
    }

    /**
     * Create an instance of {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent }
     * 
     */
    public SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent createSaglasnostZaSprovodjenjePreporuceneImunizacijePacijent() {
        return new SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent();
    }

    /**
     * Create an instance of {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Drzavljanstvo }
     * 
     */
    public SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Drzavljanstvo createSaglasnostZaSprovodjenjePreporuceneImunizacijePacijentDrzavljanstvo() {
        return new SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Drzavljanstvo();
    }

    /**
     * Create an instance of {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.IzjavaSaglasnosti }
     * 
     */
    public SaglasnostZaSprovodjenjePreporuceneImunizacije.IzjavaSaglasnosti createSaglasnostZaSprovodjenjePreporuceneImunizacijeIzjavaSaglasnosti() {
        return new SaglasnostZaSprovodjenjePreporuceneImunizacije.IzjavaSaglasnosti();
    }

    /**
     * Create an instance of {@link TlicneInformacije }
     * 
     */
    public TlicneInformacije createTlicneInformacije() {
        return new TlicneInformacije();
    }

    /**
     * Create an instance of {@link Tlekar }
     * 
     */
    public Tlekar createTlekar() {
        return new Tlekar();
    }

    /**
     * Create an instance of {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji.Obrazac.PrimljeneVakcine }
     * 
     */
    public SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji.Obrazac.PrimljeneVakcine createSaglasnostZaSprovodjenjePreporuceneImunizacijeEvidencijaOVakcinacijiObrazacPrimljeneVakcine() {
        return new SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji.Obrazac.PrimljeneVakcine();
    }

    /**
     * Create an instance of {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji.Obrazac.PrivremeneKontraindikacije }
     * 
     */
    public SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji.Obrazac.PrivremeneKontraindikacije createSaglasnostZaSprovodjenjePreporuceneImunizacijeEvidencijaOVakcinacijiObrazacPrivremeneKontraindikacije() {
        return new SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji.Obrazac.PrivremeneKontraindikacije();
    }

    /**
     * Create an instance of {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Rodjenje }
     * 
     */
    public SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Rodjenje createSaglasnostZaSprovodjenjePreporuceneImunizacijePacijentRodjenje() {
        return new SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Rodjenje();
    }

    /**
     * Create an instance of {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Stanovanje }
     * 
     */
    public SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Stanovanje createSaglasnostZaSprovodjenjePreporuceneImunizacijePacijentStanovanje() {
        return new SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Stanovanje();
    }

    /**
     * Create an instance of {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.UstanovaSocijalneZastite }
     * 
     */
    public SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.UstanovaSocijalneZastite createSaglasnostZaSprovodjenjePreporuceneImunizacijePacijentUstanovaSocijalneZastite() {
        return new SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.UstanovaSocijalneZastite();
    }

    /**
     * Create an instance of {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Drzavljanstvo.Domace }
     * 
     */
    public SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Drzavljanstvo.Domace createSaglasnostZaSprovodjenjePreporuceneImunizacijePacijentDrzavljanstvoDomace() {
        return new SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Drzavljanstvo.Domace();
    }

    /**
     * Create an instance of {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Drzavljanstvo.Strano }
     * 
     */
    public SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Drzavljanstvo.Strano createSaglasnostZaSprovodjenjePreporuceneImunizacijePacijentDrzavljanstvoStrano() {
        return new SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Drzavljanstvo.Strano();
    }

}
