//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.07 at 03:55:17 PM CET 
//


package vakcinac.io.citizen.models.sag;

import java.math.BigInteger;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import vakcinac.io.citizen.annotations.RegisterXmlScheme;
import vakcinac.io.citizen.models.os.Tkontakt;
import vakcinac.io.citizen.utils.adapters.LocalDateAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pacijent">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="drzavljanstvo">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice>
 *                             &lt;element name="domace">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="jmbg" type="{https://www.vakcinac-io.rs/osnovna-sema}Tjmbg"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="strano">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="naziv-drzavljanstva" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="broj-pasosa-ebs" type="{https://www.vakcinac-io.rs/osnovna-sema}Tpasos"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="licne-informacije" type="{https://www.vakcinac-io.rs/saglasnost}TlicneInformacije"/>
 *                   &lt;element name="rodjenje">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="datum-rodjenja" type="{https://www.vakcinac-io.rs/osnovna-sema}TdateString"/>
 *                             &lt;element name="mesto-rodjenja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="stanovanje">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="adresa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="mesto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="opstina" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="kontakt" type="{https://www.vakcinac-io.rs/osnovna-sema}Tkontakt"/>
 *                   &lt;element name="ustanova-socijalne-zastite">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="korisnik" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="naziv-opstina-sedista" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="izjava-saglasnosti">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="izjava" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="naziv-imunoloskog-leka" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="evidencija-o-vakcinaciji">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="zdravstvena-ustanova" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="vakcinacijski-punkt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="lekar" type="{https://www.vakcinac-io.rs/saglasnost}Tlekar"/>
 *                   &lt;element name="obrazac">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="primljene-vakcine" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="datum-davanja-vakcine" type="{https://www.vakcinac-io.rs/osnovna-sema}TdateString"/>
 *                                       &lt;element name="nacin-davanja-vakcine" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ekstremitet" type="{https://www.vakcinac-io.rs/saglasnost}Tekstremitet"/>
 *                                       &lt;element name="serija-vakcine" type="{https://www.vakcinac-io.rs/osnovna-sema}Tserija"/>
 *                                       &lt;element name="proizvodjac" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="nezeljena-reakcija" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="broj" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="privremene-kontraindikacije">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="datum-utvrdjivanja" type="{https://www.vakcinac-io.rs/osnovna-sema}TdateString"/>
 *                                       &lt;element name="dijagnoza" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="odluka-komisije" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="datum-izdavanja" use="required" type="{https://www.vakcinac-io.rs/osnovna-sema}TdateString" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pacijent",
    "izjavaSaglasnosti",
    "evidencijaOVakcinaciji"
})
@XmlRootElement(name = "saglasnost-za-sprovodjenje-preporucene-imunizacije")
@RegisterXmlScheme(
	schemePath="/data/schemes/saglasnost_imunizacije.xsd",
	targetNamespace="https://www.vakcinac-io.rs/saglasnost",
	shortNamespace="sag"
)
public class SaglasnostZaSprovodjenjePreporuceneImunizacije {

    @XmlElement(required = true)
    protected SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent pacijent;
    @XmlElement(name = "izjava-saglasnosti", required = true)
    protected SaglasnostZaSprovodjenjePreporuceneImunizacije.IzjavaSaglasnosti izjavaSaglasnosti;
    @XmlElement(name = "evidencija-o-vakcinaciji", required = true)
    protected SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji evidencijaOVakcinaciji;
    @XmlAttribute(name = "datum-izdavanja", required = true)
    @XmlJavaTypeAdapter(LocalDateAdapter.class)
    protected LocalDate datumIzdavanja;

    /**
     * Gets the value of the pacijent property.
     * 
     * @return
     *     possible object is
     *     {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent }
     *     
     */
    public SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent getPacijent() {
        return pacijent;
    }

    /**
     * Sets the value of the pacijent property.
     * 
     * @param value
     *     allowed object is
     *     {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent }
     *     
     */
    public void setPacijent(SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent value) {
        this.pacijent = value;
    }

    /**
     * Gets the value of the izjavaSaglasnosti property.
     * 
     * @return
     *     possible object is
     *     {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.IzjavaSaglasnosti }
     *     
     */
    public SaglasnostZaSprovodjenjePreporuceneImunizacije.IzjavaSaglasnosti getIzjavaSaglasnosti() {
        return izjavaSaglasnosti;
    }

    /**
     * Sets the value of the izjavaSaglasnosti property.
     * 
     * @param value
     *     allowed object is
     *     {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.IzjavaSaglasnosti }
     *     
     */
    public void setIzjavaSaglasnosti(SaglasnostZaSprovodjenjePreporuceneImunizacije.IzjavaSaglasnosti value) {
        this.izjavaSaglasnosti = value;
    }

    /**
     * Gets the value of the evidencijaOVakcinaciji property.
     * 
     * @return
     *     possible object is
     *     {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji }
     *     
     */
    public SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji getEvidencijaOVakcinaciji() {
        return evidencijaOVakcinaciji;
    }

    /**
     * Sets the value of the evidencijaOVakcinaciji property.
     * 
     * @param value
     *     allowed object is
     *     {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji }
     *     
     */
    public void setEvidencijaOVakcinaciji(SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji value) {
        this.evidencijaOVakcinaciji = value;
    }

    /**
     * Gets the value of the datumIzdavanja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public LocalDate getDatumIzdavanja() {
        return datumIzdavanja;
    }

    /**
     * Sets the value of the datumIzdavanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatumIzdavanja(LocalDate value) {
        this.datumIzdavanja = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="zdravstvena-ustanova" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="vakcinacijski-punkt" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="lekar" type="{https://www.vakcinac-io.rs/saglasnost}Tlekar"/>
     *         &lt;element name="obrazac">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="primljene-vakcine" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="datum-davanja-vakcine" type="{https://www.vakcinac-io.rs/osnovna-sema}TdateString"/>
     *                             &lt;element name="nacin-davanja-vakcine" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ekstremitet" type="{https://www.vakcinac-io.rs/saglasnost}Tekstremitet"/>
     *                             &lt;element name="serija-vakcine" type="{https://www.vakcinac-io.rs/osnovna-sema}Tserija"/>
     *                             &lt;element name="proizvodjac" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="nezeljena-reakcija" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="broj" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="privremene-kontraindikacije">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="datum-utvrdjivanja" type="{https://www.vakcinac-io.rs/osnovna-sema}TdateString"/>
     *                             &lt;element name="dijagnoza" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="odluka-komisije" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "zdravstvenaUstanova",
        "vakcinacijskiPunkt",
        "lekar",
        "obrazac"
    })
    public static class EvidencijaOVakcinaciji {

        @XmlElement(name = "zdravstvena-ustanova", required = true)
        protected String zdravstvenaUstanova;
        @XmlElement(name = "vakcinacijski-punkt", required = true)
        protected String vakcinacijskiPunkt;
        @XmlElement(required = true)
        protected Tlekar lekar;
        @XmlElement(required = true)
        protected SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji.Obrazac obrazac;

        /**
         * Gets the value of the zdravstvenaUstanova property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getZdravstvenaUstanova() {
            return zdravstvenaUstanova;
        }

        /**
         * Sets the value of the zdravstvenaUstanova property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setZdravstvenaUstanova(String value) {
            this.zdravstvenaUstanova = value;
        }

        /**
         * Gets the value of the vakcinacijskiPunkt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVakcinacijskiPunkt() {
            return vakcinacijskiPunkt;
        }

        /**
         * Sets the value of the vakcinacijskiPunkt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVakcinacijskiPunkt(String value) {
            this.vakcinacijskiPunkt = value;
        }

        /**
         * Gets the value of the lekar property.
         * 
         * @return
         *     possible object is
         *     {@link Tlekar }
         *     
         */
        public Tlekar getLekar() {
            return lekar;
        }

        /**
         * Sets the value of the lekar property.
         * 
         * @param value
         *     allowed object is
         *     {@link Tlekar }
         *     
         */
        public void setLekar(Tlekar value) {
            this.lekar = value;
        }

        /**
         * Gets the value of the obrazac property.
         * 
         * @return
         *     possible object is
         *     {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji.Obrazac }
         *     
         */
        public SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji.Obrazac getObrazac() {
            return obrazac;
        }

        /**
         * Sets the value of the obrazac property.
         * 
         * @param value
         *     allowed object is
         *     {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji.Obrazac }
         *     
         */
        public void setObrazac(SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji.Obrazac value) {
            this.obrazac = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="primljene-vakcine" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="datum-davanja-vakcine" type="{https://www.vakcinac-io.rs/osnovna-sema}TdateString"/>
         *                   &lt;element name="nacin-davanja-vakcine" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ekstremitet" type="{https://www.vakcinac-io.rs/saglasnost}Tekstremitet"/>
         *                   &lt;element name="serija-vakcine" type="{https://www.vakcinac-io.rs/osnovna-sema}Tserija"/>
         *                   &lt;element name="proizvodjac" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="nezeljena-reakcija" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="broj" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="privremene-kontraindikacije">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="datum-utvrdjivanja" type="{https://www.vakcinac-io.rs/osnovna-sema}TdateString"/>
         *                   &lt;element name="dijagnoza" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="odluka-komisije" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "primljeneVakcine",
            "privremeneKontraindikacije"
        })
        public static class Obrazac {

            @XmlElement(name = "primljene-vakcine")
            protected List<SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji.Obrazac.PrimljeneVakcine> primljeneVakcine;
            @XmlElement(name = "privremene-kontraindikacije", required = true)
            protected SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji.Obrazac.PrivremeneKontraindikacije privremeneKontraindikacije;

            /**
             * Gets the value of the primljeneVakcine property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the primljeneVakcine property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPrimljeneVakcine().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji.Obrazac.PrimljeneVakcine }
             * 
             * 
             */
            public List<SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji.Obrazac.PrimljeneVakcine> getPrimljeneVakcine() {
                if (primljeneVakcine == null) {
                    primljeneVakcine = new ArrayList<SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji.Obrazac.PrimljeneVakcine>();
                }
                return this.primljeneVakcine;
            }

            /**
             * Gets the value of the privremeneKontraindikacije property.
             * 
             * @return
             *     possible object is
             *     {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji.Obrazac.PrivremeneKontraindikacije }
             *     
             */
            public SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji.Obrazac.PrivremeneKontraindikacije getPrivremeneKontraindikacije() {
                return privremeneKontraindikacije;
            }

            /**
             * Sets the value of the privremeneKontraindikacije property.
             * 
             * @param value
             *     allowed object is
             *     {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji.Obrazac.PrivremeneKontraindikacije }
             *     
             */
            public void setPrivremeneKontraindikacije(SaglasnostZaSprovodjenjePreporuceneImunizacije.EvidencijaOVakcinaciji.Obrazac.PrivremeneKontraindikacije value) {
                this.privremeneKontraindikacije = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="datum-davanja-vakcine" type="{https://www.vakcinac-io.rs/osnovna-sema}TdateString"/>
             *         &lt;element name="nacin-davanja-vakcine" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ekstremitet" type="{https://www.vakcinac-io.rs/saglasnost}Tekstremitet"/>
             *         &lt;element name="serija-vakcine" type="{https://www.vakcinac-io.rs/osnovna-sema}Tserija"/>
             *         &lt;element name="proizvodjac" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="nezeljena-reakcija" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *       &lt;attribute name="broj" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "naziv",
                "datumDavanjaVakcine",
                "nacinDavanjaVakcine",
                "ekstremitet",
                "serijaVakcine",
                "proizvodjac",
                "nezeljenaReakcija"
            })
            public static class PrimljeneVakcine {

                @XmlElement(required = true, nillable = true)
                protected String naziv;
                @XmlElement(name = "datum-davanja-vakcine", required = true, type = String.class, nillable = true)
                @XmlJavaTypeAdapter(LocalDateAdapter.class)
                protected LocalDate datumDavanjaVakcine;
                @XmlElement(name = "nacin-davanja-vakcine", required = true, nillable = true)
                protected String nacinDavanjaVakcine;
                @XmlElement(required = true, type = Integer.class, nillable = true)
                protected Integer ekstremitet;
                @XmlElement(name = "serija-vakcine", required = true, nillable = true)
                protected String serijaVakcine;
                @XmlElement(required = true, nillable = true)
                protected String proizvodjac;
                @XmlElement(name = "nezeljena-reakcija", required = true, nillable = true)
                protected String nezeljenaReakcija;
                @XmlAttribute(name = "broj", required = true)
                @XmlSchemaType(name = "positiveInteger")
                protected BigInteger broj;

                /**
                 * Gets the value of the naziv property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNaziv() {
                    return naziv;
                }

                /**
                 * Sets the value of the naziv property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNaziv(String value) {
                    this.naziv = value;
                }

                /**
                 * Gets the value of the datumDavanjaVakcine property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public LocalDate getDatumDavanjaVakcine() {
                    return datumDavanjaVakcine;
                }

                /**
                 * Sets the value of the datumDavanjaVakcine property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDatumDavanjaVakcine(LocalDate value) {
                    this.datumDavanjaVakcine = value;
                }

                /**
                 * Gets the value of the nacinDavanjaVakcine property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNacinDavanjaVakcine() {
                    return nacinDavanjaVakcine;
                }

                /**
                 * Sets the value of the nacinDavanjaVakcine property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNacinDavanjaVakcine(String value) {
                    this.nacinDavanjaVakcine = value;
                }

                /**
                 * Gets the value of the ekstremitet property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getEkstremitet() {
                    return ekstremitet;
                }

                /**
                 * Sets the value of the ekstremitet property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setEkstremitet(Integer value) {
                    this.ekstremitet = value;
                }

                /**
                 * Gets the value of the serijaVakcine property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSerijaVakcine() {
                    return serijaVakcine;
                }

                /**
                 * Sets the value of the serijaVakcine property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSerijaVakcine(String value) {
                    this.serijaVakcine = value;
                }

                /**
                 * Gets the value of the proizvodjac property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getProizvodjac() {
                    return proizvodjac;
                }

                /**
                 * Sets the value of the proizvodjac property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setProizvodjac(String value) {
                    this.proizvodjac = value;
                }

                /**
                 * Gets the value of the nezeljenaReakcija property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNezeljenaReakcija() {
                    return nezeljenaReakcija;
                }

                /**
                 * Sets the value of the nezeljenaReakcija property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNezeljenaReakcija(String value) {
                    this.nezeljenaReakcija = value;
                }

                /**
                 * Gets the value of the broj property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getBroj() {
                    return broj;
                }

                /**
                 * Sets the value of the broj property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setBroj(BigInteger value) {
                    this.broj = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="datum-utvrdjivanja" type="{https://www.vakcinac-io.rs/osnovna-sema}TdateString"/>
             *         &lt;element name="dijagnoza" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="odluka-komisije" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "datumUtvrdjivanja",
                "dijagnoza",
                "odlukaKomisije"
            })
            public static class PrivremeneKontraindikacije {

                @XmlElement(name = "datum-utvrdjivanja", required = true, type = String.class, nillable = true)
                @XmlJavaTypeAdapter(LocalDateAdapter.class)
                protected LocalDate datumUtvrdjivanja;
                @XmlElement(required = true, nillable = true)
                protected String dijagnoza;
                @XmlElement(name = "odluka-komisije", required = true, type = Boolean.class, nillable = true)
                protected Boolean odlukaKomisije;

                /**
                 * Gets the value of the datumUtvrdjivanja property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public LocalDate getDatumUtvrdjivanja() {
                    return datumUtvrdjivanja;
                }

                /**
                 * Sets the value of the datumUtvrdjivanja property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDatumUtvrdjivanja(LocalDate value) {
                    this.datumUtvrdjivanja = value;
                }

                /**
                 * Gets the value of the dijagnoza property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDijagnoza() {
                    return dijagnoza;
                }

                /**
                 * Sets the value of the dijagnoza property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDijagnoza(String value) {
                    this.dijagnoza = value;
                }

                /**
                 * Gets the value of the odlukaKomisije property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *     
                 */
                public Boolean isOdlukaKomisije() {
                    return odlukaKomisije;
                }

                /**
                 * Sets the value of the odlukaKomisije property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *     
                 */
                public void setOdlukaKomisije(Boolean value) {
                    this.odlukaKomisije = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="izjava" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="naziv-imunoloskog-leka" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "izjava",
        "nazivImunoloskogLeka"
    })
    public static class IzjavaSaglasnosti {

        protected boolean izjava;
        @XmlElement(name = "naziv-imunoloskog-leka", required = true)
        protected String nazivImunoloskogLeka;

        /**
         * Gets the value of the izjava property.
         * 
         */
        public boolean isIzjava() {
            return izjava;
        }

        /**
         * Sets the value of the izjava property.
         * 
         */
        public void setIzjava(boolean value) {
            this.izjava = value;
        }

        /**
         * Gets the value of the nazivImunoloskogLeka property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNazivImunoloskogLeka() {
            return nazivImunoloskogLeka;
        }

        /**
         * Sets the value of the nazivImunoloskogLeka property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNazivImunoloskogLeka(String value) {
            this.nazivImunoloskogLeka = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="drzavljanstvo">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element name="domace">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="jmbg" type="{https://www.vakcinac-io.rs/osnovna-sema}Tjmbg"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="strano">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="naziv-drzavljanstva" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="broj-pasosa-ebs" type="{https://www.vakcinac-io.rs/osnovna-sema}Tpasos"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="licne-informacije" type="{https://www.vakcinac-io.rs/saglasnost}TlicneInformacije"/>
     *         &lt;element name="rodjenje">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="datum-rodjenja" type="{https://www.vakcinac-io.rs/osnovna-sema}TdateString"/>
     *                   &lt;element name="mesto-rodjenja" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="stanovanje">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="adresa" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="mesto" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="opstina" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="kontakt" type="{https://www.vakcinac-io.rs/osnovna-sema}Tkontakt"/>
     *         &lt;element name="ustanova-socijalne-zastite">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="korisnik" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="naziv-opstina-sedista" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "drzavljanstvo",
        "licneInformacije",
        "rodjenje",
        "stanovanje",
        "kontakt",
        "ustanovaSocijalneZastite"
    })
    public static class Pacijent {

        @XmlElement(required = true)
        protected SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Drzavljanstvo drzavljanstvo;
        @XmlElement(name = "licne-informacije", required = true)
        protected TlicneInformacije licneInformacije;
        @XmlElement(required = true)
        protected SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Rodjenje rodjenje;
        @XmlElement(required = true)
        protected SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Stanovanje stanovanje;
        @XmlElement(required = true)
        protected Tkontakt kontakt;
        @XmlElement(name = "ustanova-socijalne-zastite", required = true)
        protected SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.UstanovaSocijalneZastite ustanovaSocijalneZastite;

        /**
         * Gets the value of the drzavljanstvo property.
         * 
         * @return
         *     possible object is
         *     {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Drzavljanstvo }
         *     
         */
        public SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Drzavljanstvo getDrzavljanstvo() {
            return drzavljanstvo;
        }

        /**
         * Sets the value of the drzavljanstvo property.
         * 
         * @param value
         *     allowed object is
         *     {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Drzavljanstvo }
         *     
         */
        public void setDrzavljanstvo(SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Drzavljanstvo value) {
            this.drzavljanstvo = value;
        }

        /**
         * Gets the value of the licneInformacije property.
         * 
         * @return
         *     possible object is
         *     {@link TlicneInformacije }
         *     
         */
        public TlicneInformacije getLicneInformacije() {
            return licneInformacije;
        }

        /**
         * Sets the value of the licneInformacije property.
         * 
         * @param value
         *     allowed object is
         *     {@link TlicneInformacije }
         *     
         */
        public void setLicneInformacije(TlicneInformacije value) {
            this.licneInformacije = value;
        }

        /**
         * Gets the value of the rodjenje property.
         * 
         * @return
         *     possible object is
         *     {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Rodjenje }
         *     
         */
        public SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Rodjenje getRodjenje() {
            return rodjenje;
        }

        /**
         * Sets the value of the rodjenje property.
         * 
         * @param value
         *     allowed object is
         *     {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Rodjenje }
         *     
         */
        public void setRodjenje(SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Rodjenje value) {
            this.rodjenje = value;
        }

        /**
         * Gets the value of the stanovanje property.
         * 
         * @return
         *     possible object is
         *     {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Stanovanje }
         *     
         */
        public SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Stanovanje getStanovanje() {
            return stanovanje;
        }

        /**
         * Sets the value of the stanovanje property.
         * 
         * @param value
         *     allowed object is
         *     {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Stanovanje }
         *     
         */
        public void setStanovanje(SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Stanovanje value) {
            this.stanovanje = value;
        }

        /**
         * Gets the value of the kontakt property.
         * 
         * @return
         *     possible object is
         *     {@link Tkontakt }
         *     
         */
        public Tkontakt getKontakt() {
            return kontakt;
        }

        /**
         * Sets the value of the kontakt property.
         * 
         * @param value
         *     allowed object is
         *     {@link Tkontakt }
         *     
         */
        public void setKontakt(Tkontakt value) {
            this.kontakt = value;
        }

        /**
         * Gets the value of the ustanovaSocijalneZastite property.
         * 
         * @return
         *     possible object is
         *     {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.UstanovaSocijalneZastite }
         *     
         */
        public SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.UstanovaSocijalneZastite getUstanovaSocijalneZastite() {
            return ustanovaSocijalneZastite;
        }

        /**
         * Sets the value of the ustanovaSocijalneZastite property.
         * 
         * @param value
         *     allowed object is
         *     {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.UstanovaSocijalneZastite }
         *     
         */
        public void setUstanovaSocijalneZastite(SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.UstanovaSocijalneZastite value) {
            this.ustanovaSocijalneZastite = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="domace">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="jmbg" type="{https://www.vakcinac-io.rs/osnovna-sema}Tjmbg"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="strano">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="naziv-drzavljanstva" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="broj-pasosa-ebs" type="{https://www.vakcinac-io.rs/osnovna-sema}Tpasos"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "domace",
            "strano"
        })
        public static class Drzavljanstvo {

            protected SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Drzavljanstvo.Domace domace;
            protected SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Drzavljanstvo.Strano strano;

            /**
             * Gets the value of the domace property.
             * 
             * @return
             *     possible object is
             *     {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Drzavljanstvo.Domace }
             *     
             */
            public SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Drzavljanstvo.Domace getDomace() {
                return domace;
            }

            /**
             * Sets the value of the domace property.
             * 
             * @param value
             *     allowed object is
             *     {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Drzavljanstvo.Domace }
             *     
             */
            public void setDomace(SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Drzavljanstvo.Domace value) {
                this.domace = value;
            }

            /**
             * Gets the value of the strano property.
             * 
             * @return
             *     possible object is
             *     {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Drzavljanstvo.Strano }
             *     
             */
            public SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Drzavljanstvo.Strano getStrano() {
                return strano;
            }

            /**
             * Sets the value of the strano property.
             * 
             * @param value
             *     allowed object is
             *     {@link SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Drzavljanstvo.Strano }
             *     
             */
            public void setStrano(SaglasnostZaSprovodjenjePreporuceneImunizacije.Pacijent.Drzavljanstvo.Strano value) {
                this.strano = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="jmbg" type="{https://www.vakcinac-io.rs/osnovna-sema}Tjmbg"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "jmbg"
            })
            public static class Domace {

                @XmlElement(required = true)
                protected String jmbg;

                /**
                 * Gets the value of the jmbg property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getJmbg() {
                    return jmbg;
                }

                /**
                 * Sets the value of the jmbg property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setJmbg(String value) {
                    this.jmbg = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="naziv-drzavljanstva" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="broj-pasosa-ebs" type="{https://www.vakcinac-io.rs/osnovna-sema}Tpasos"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "nazivDrzavljanstva",
                "brojPasosaEbs"
            })
            public static class Strano {

                @XmlElement(name = "naziv-drzavljanstva", required = true)
                protected String nazivDrzavljanstva;
                @XmlElement(name = "broj-pasosa-ebs", required = true)
                protected String brojPasosaEbs;

                /**
                 * Gets the value of the nazivDrzavljanstva property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNazivDrzavljanstva() {
                    return nazivDrzavljanstva;
                }

                /**
                 * Sets the value of the nazivDrzavljanstva property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNazivDrzavljanstva(String value) {
                    this.nazivDrzavljanstva = value;
                }

                /**
                 * Gets the value of the brojPasosaEbs property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBrojPasosaEbs() {
                    return brojPasosaEbs;
                }

                /**
                 * Sets the value of the brojPasosaEbs property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBrojPasosaEbs(String value) {
                    this.brojPasosaEbs = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="datum-rodjenja" type="{https://www.vakcinac-io.rs/osnovna-sema}TdateString"/>
         *         &lt;element name="mesto-rodjenja" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "datumRodjenja",
            "mestoRodjenja"
        })
        public static class Rodjenje {

            @XmlElement(name = "datum-rodjenja", required = true, type = String.class)
            @XmlJavaTypeAdapter(LocalDateAdapter.class)
            protected LocalDate datumRodjenja;
            @XmlElement(name = "mesto-rodjenja", required = true)
            protected String mestoRodjenja;

            /**
             * Gets the value of the datumRodjenja property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public LocalDate getDatumRodjenja() {
                return datumRodjenja;
            }

            /**
             * Sets the value of the datumRodjenja property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDatumRodjenja(LocalDate value) {
                this.datumRodjenja = value;
            }

            /**
             * Gets the value of the mestoRodjenja property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMestoRodjenja() {
                return mestoRodjenja;
            }

            /**
             * Sets the value of the mestoRodjenja property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMestoRodjenja(String value) {
                this.mestoRodjenja = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="adresa" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="mesto" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="opstina" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "adresa",
            "mesto",
            "opstina"
        })
        public static class Stanovanje {

            @XmlElement(required = true)
            protected String adresa;
            @XmlElement(required = true)
            protected String mesto;
            @XmlElement(required = true)
            protected String opstina;

            /**
             * Gets the value of the adresa property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAdresa() {
                return adresa;
            }

            /**
             * Sets the value of the adresa property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAdresa(String value) {
                this.adresa = value;
            }

            /**
             * Gets the value of the mesto property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMesto() {
                return mesto;
            }

            /**
             * Sets the value of the mesto property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMesto(String value) {
                this.mesto = value;
            }

            /**
             * Gets the value of the opstina property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOpstina() {
                return opstina;
            }

            /**
             * Sets the value of the opstina property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOpstina(String value) {
                this.opstina = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="korisnik" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="naziv-opstina-sedista" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "korisnik",
            "nazivOpstinaSedista"
        })
        public static class UstanovaSocijalneZastite {

            protected boolean korisnik;
            @XmlElement(name = "naziv-opstina-sedista", required = true)
            protected String nazivOpstinaSedista;

            /**
             * Gets the value of the korisnik property.
             * 
             */
            public boolean isKorisnik() {
                return korisnik;
            }

            /**
             * Sets the value of the korisnik property.
             * 
             */
            public void setKorisnik(boolean value) {
                this.korisnik = value;
            }

            /**
             * Gets the value of the nazivOpstinaSedista property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNazivOpstinaSedista() {
                return nazivOpstinaSedista;
            }

            /**
             * Sets the value of the nazivOpstinaSedista property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNazivOpstinaSedista(String value) {
                this.nazivOpstinaSedista = value;
            }

        }

    }

}
