//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 10:51:44 PM CET 
//


package vakcinac.io.citizen.models.sag;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import vakcinac.io.citizen.models.os.Tosoba;


/**
 * <p>Java class for TlicneInformacije complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TlicneInformacije">
 *   &lt;complexContent>
 *     &lt;extension base="{https://www.vakcinac-io.rs/osnovna-sema}Tosoba">
 *       &lt;sequence>
 *         &lt;element name="ime-roditelja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pol" type="{https://www.vakcinac-io.rs/osnovna-sema}Tpol"/>
 *         &lt;element name="radni-status" type="{https://www.vakcinac-io.rs/saglasnost}TradniStatus"/>
 *         &lt;element name="zanimanje" type="{https://www.vakcinac-io.rs/saglasnost}Tzanimanje"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TlicneInformacije", propOrder = {
    "imeRoditelja",
    "pol",
    "radniStatus",
    "zanimanje"
})
public class TlicneInformacije
    extends Tosoba
{

    @XmlElement(name = "ime-roditelja", required = true)
    protected String imeRoditelja;
    protected int pol;
    @XmlElement(name = "radni-status")
    protected int radniStatus;
    protected int zanimanje;

    /**
     * Gets the value of the imeRoditelja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImeRoditelja() {
        return imeRoditelja;
    }

    /**
     * Sets the value of the imeRoditelja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImeRoditelja(String value) {
        this.imeRoditelja = value;
    }

    /**
     * Gets the value of the pol property.
     * 
     */
    public int getPol() {
        return pol;
    }

    /**
     * Sets the value of the pol property.
     * 
     */
    public void setPol(int value) {
        this.pol = value;
    }

    /**
     * Gets the value of the radniStatus property.
     * 
     */
    public int getRadniStatus() {
        return radniStatus;
    }

    /**
     * Sets the value of the radniStatus property.
     * 
     */
    public void setRadniStatus(int value) {
        this.radniStatus = value;
    }

    /**
     * Gets the value of the zanimanje property.
     * 
     */
    public int getZanimanje() {
        return zanimanje;
    }

    /**
     * Sets the value of the zanimanje property.
     * 
     */
    public void setZanimanje(int value) {
        this.zanimanje = value;
    }

}
