//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 10:51:46 PM CET 
//


package vakcinac.io.core.models.trans;

import vakcinac.io.core.annotations.RegisterExistEntity;
import vakcinac.io.core.annotations.RegisterXmlScheme;
import vakcinac.io.core.annotations.RegisterXslFo;
import vakcinac.io.core.annotations.RegisterXslt;
import vakcinac.io.core.models.os.Tlink;
import vakcinac.io.core.models.os.Tmeta;
import vakcinac.io.core.utils.adapters.LocalDateAdapter;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="link" type="{https://www.vakcinac-io.rs/osnovna-sema}Tlink" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="meta" type="{https://www.vakcinac-io.rs/osnovna-sema}Tmeta" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="podnosilac-zahteva" type="{https://www.vakcinac-io.rs/zahtev}TpodnosilacZahteva"/>
 *         &lt;element name="razlog" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{https://www.vakcinac-io.rs/osnovna-sema}rdfMainDocument"/>
 *       &lt;attribute name="dan" type="{https://www.vakcinac-io.rs/osnovna-sema}TdateString" />
 *       &lt;attribute name="mesto" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "link",
    "meta",
    "podnosilacZahteva",
    "razlog"
})
@XmlRootElement(name = "zahtev-za-izdavanje-zelenog-sertifikata")
@RegisterXmlScheme(
	schemePath="/data/schemes/zahtev_za_zeleni_sertifikat.xsd",
	targetNamespace="https://www.vakcinac-io.rs/zahtev",
	shortNamespace="zah"
)
@RegisterExistEntity(
	collectionUri="db/zahtevi"
)
@RegisterXslt(
	xslPath="/data/xslt/zahtev_za_izdavanje_zelenog_sertifikata.xsl"
)
@RegisterXslFo(
	xslPath="/data/xsl-fo/zahtev_za_izdavanje_zelenog_sertifikata.xsl"
)
public class ZahtevZaIzdavanjeZelenogSertifikata {

    protected List<Tlink> link;
    protected List<Tmeta> meta;
    @XmlElement(name = "podnosilac-zahteva", required = true)
    protected TpodnosilacZahteva podnosilacZahteva;
    @XmlElement(required = true)
    protected String razlog;
    @XmlAttribute(name = "dan")
    @XmlJavaTypeAdapter(LocalDateAdapter.class)
    protected LocalDate dan;
    @XmlAttribute(name = "mesto")
    protected String mesto;
    @XmlAttribute(name = "about")
    @XmlSchemaType(name = "anySimpleType")
    protected String about;
    @XmlAttribute(name = "typeof")
    @XmlSchemaType(name = "anySimpleType")
    protected String typeof;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the link property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the link property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tlink }
     * 
     * 
     */
    public List<Tlink> getLink() {
        if (link == null) {
            link = new ArrayList<Tlink>();
        }
        return this.link;
    }

    /**
     * Gets the value of the meta property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the meta property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeta().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tmeta }
     * 
     * 
     */
    public List<Tmeta> getMeta() {
        if (meta == null) {
            meta = new ArrayList<Tmeta>();
        }
        return this.meta;
    }

    /**
     * Gets the value of the podnosilacZahteva property.
     * 
     * @return
     *     possible object is
     *     {@link TpodnosilacZahteva }
     *     
     */
    public TpodnosilacZahteva getPodnosilacZahteva() {
        return podnosilacZahteva;
    }

    /**
     * Sets the value of the podnosilacZahteva property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpodnosilacZahteva }
     *     
     */
    public void setPodnosilacZahteva(TpodnosilacZahteva value) {
        this.podnosilacZahteva = value;
    }

    /**
     * Gets the value of the razlog property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRazlog() {
        return razlog;
    }

    /**
     * Sets the value of the razlog property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRazlog(String value) {
        this.razlog = value;
    }

    /**
     * Gets the value of the dan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public LocalDate getDan() {
        return dan;
    }

    /**
     * Sets the value of the dan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDan(LocalDate value) {
        this.dan = value;
    }

    /**
     * Gets the value of the mesto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMesto() {
        return mesto;
    }

    /**
     * Sets the value of the mesto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMesto(String value) {
        this.mesto = value;
    }

    /**
     * Gets the value of the about property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbout(String value) {
        this.about = value;
    }

    /**
     * Gets the value of the typeof property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeof() {
        return typeof;
    }

    /**
     * Sets the value of the typeof property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeof(String value) {
        this.typeof = value;
    }
    
    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
