//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.13 at 02:52:40 PM CET 
//


package vakcinac.io.core.models.os;

import javax.xml.bind.annotation.XmlRegistry;

import vakcinac.io.core.annotations.RegisterXmlScheme;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the vakcinac.io.core.models.os package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
@RegisterXmlScheme(
	schemePath = "/data/schemes/osnovna_sema.xsd",
	targetNamespace="https://www.vakcinac-io.rs/osnovna-sema",
	shortNamespace="os"
)
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: vakcinac.io.core.models.os
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TosobaSaJmbg }
     * 
     */
    public TosobaSaJmbg createTosobaSaJmbg() {
        return new TosobaSaJmbg();
    }

    /**
     * Create an instance of {@link Tkontakt }
     * 
     */
    public Tkontakt createTkontakt() {
        return new Tkontakt();
    }

    /**
     * Create an instance of {@link Tkorisnik }
     * 
     */
    public Tkorisnik createTkorisnik() {
        return new Tkorisnik();
    }

    /**
     * Create an instance of {@link Tmeta }
     * 
     */
    public Tmeta createTmeta() {
        return new Tmeta();
    }

    /**
     * Create an instance of {@link Tgradjanin }
     * 
     */
    public Tgradjanin createTgradjanin() {
        return new Tgradjanin();
    }

    /**
     * Create an instance of {@link Tlink }
     * 
     */
    public Tlink createTlink() {
        return new Tlink();
    }

    /**
     * Create an instance of {@link Tosoba }
     * 
     */
    public Tosoba createTosoba() {
        return new Tosoba();
    }

}
