//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.16 at 02:01:11 PM CET 
//


package vakcinac.io.core.models.os;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Tkontakt complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Tkontakt">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="adresa-elektronske-poste" type="{https://www.vakcinac-io.rs/osnovna-sema}Temail"/>
 *         &lt;element name="broj-mobilnog-telefona" type="{https://www.vakcinac-io.rs/osnovna-sema}TbrMob"/>
 *         &lt;element name="broj-fiksnog-telefona" type="{https://www.vakcinac-io.rs/osnovna-sema}TbrFiks"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tkontakt", propOrder = {
    "adresaElektronskePoste",
    "brojMobilnogTelefona",
    "brojFiksnogTelefona"
})
public class Tkontakt {

    @XmlElement(name = "adresa-elektronske-poste", required = true)
    protected String adresaElektronskePoste;
    @XmlElement(name = "broj-mobilnog-telefona", required = true)
    protected String brojMobilnogTelefona;
    @XmlElement(name = "broj-fiksnog-telefona", required = true)
    protected String brojFiksnogTelefona;

    /**
     * Gets the value of the adresaElektronskePoste property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdresaElektronskePoste() {
        return adresaElektronskePoste;
    }

    /**
     * Sets the value of the adresaElektronskePoste property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdresaElektronskePoste(String value) {
        this.adresaElektronskePoste = value;
    }

    /**
     * Gets the value of the brojMobilnogTelefona property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojMobilnogTelefona() {
        return brojMobilnogTelefona;
    }

    /**
     * Sets the value of the brojMobilnogTelefona property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojMobilnogTelefona(String value) {
        this.brojMobilnogTelefona = value;
    }

    /**
     * Gets the value of the brojFiksnogTelefona property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojFiksnogTelefona() {
        return brojFiksnogTelefona;
    }

    /**
     * Sets the value of the brojFiksnogTelefona property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojFiksnogTelefona(String value) {
        this.brojFiksnogTelefona = value;
    }

}
