//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.07 at 03:55:26 PM CET 
//


package vakcinac.io.citizen.models.zah;

import java.time.LocalDate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import vakcinac.io.citizen.annotations.RegisterExistEntity;
import vakcinac.io.citizen.annotations.RegisterXmlScheme;
import vakcinac.io.citizen.annotations.RegisterXslFo;
import vakcinac.io.citizen.annotations.RegisterXslt;
import vakcinac.io.citizen.utils.adapters.LocalDateAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="podnosilac-zahteva" type="{https://www.vakcinac-io.rs/zahtev}TpodnosilacZahteva"/>
 *         &lt;element name="razlog" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="dan" type="{https://www.vakcinac-io.rs/osnovna-sema}TdateString" />
 *       &lt;attribute name="mesto" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "podnosilacZahteva",
    "razlog"
})
@XmlRootElement(name = "zahtev-za-izdavanje-zelenog-sertifikata")
@RegisterXmlScheme(
	schemePath="/data/schemes/zahtev_za_zeleni_sertifikat.xsd",
	targetNamespace="https://www.vakcinac-io.rs/zahtev",
	shortNamespace="zah"
)
@RegisterExistEntity(
	collectionUri="db/zahtevi"
)
@RegisterXslt(
	xslPath="/data/xslt/zahtev_za_izdavanje_zelenog_sertifikata.xsl"
)
@RegisterXslFo(
	xslPath="/data/xsl-fo/zahtev_za_izdavanje_zelenog_sertifikata.xsl"
)
public class ZahtevZaIzdavanjeZelenogSertifikata {

    @XmlElement(name = "podnosilac-zahteva", required = true)
    protected TpodnosilacZahteva podnosilacZahteva;
    @XmlElement(required = true)
    protected String razlog;
    @XmlAttribute(name = "dan")
    @XmlJavaTypeAdapter(LocalDateAdapter.class)
    protected LocalDate dan;
    @XmlAttribute(name = "mesto")
    protected String mesto;

    /**
     * Gets the value of the podnosilacZahteva property.
     * 
     * @return
     *     possible object is
     *     {@link TpodnosilacZahteva }
     *     
     */
    public TpodnosilacZahteva getPodnosilacZahteva() {
        return podnosilacZahteva;
    }

    /**
     * Sets the value of the podnosilacZahteva property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpodnosilacZahteva }
     *     
     */
    public void setPodnosilacZahteva(TpodnosilacZahteva value) {
        this.podnosilacZahteva = value;
    }

    /**
     * Gets the value of the razlog property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRazlog() {
        return razlog;
    }

    /**
     * Sets the value of the razlog property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRazlog(String value) {
        this.razlog = value;
    }

    /**
     * Gets the value of the dan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public LocalDate getDan() {
        return dan;
    }

    /**
     * Sets the value of the dan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDan(LocalDate value) {
        this.dan = value;
    }

    /**
     * Gets the value of the mesto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMesto() {
        return mesto;
    }

    /**
     * Sets the value of the mesto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMesto(String value) {
        this.mesto = value;
    }

}
