//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.13 at 03:27:26 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://www.vakcinac-io.rs/stanje_vakcina", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package vakcinac.io.civil.servant.models.stanj;
