//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.13 at 03:27:26 PM CET 
//


package vakcinac.io.civil.servant.models.stanj;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import vakcinac.io.core.annotations.RegisterExistEntity;
import vakcinac.io.core.annotations.RegisterXmlScheme;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="stanje_vakcine">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="vakcina" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="dostupno" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                   &lt;element name="rezervisano" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stanjeVakcine"
})
@XmlRootElement(name = "stanje_vakcina")
@RegisterXmlScheme(
	schemePath="/data/schemes/stanje_vakcina.xsd",
	targetNamespace="https://www.vakcinac-io.rs/stanje_vakcina",
	shortNamespace="stanj"
)
@RegisterExistEntity(
	collectionUri="db/vakcine"
)
public class StanjeVakcina {

    @XmlElement(name = "stanje_vakcine")
    protected List<StanjeVakcina.StanjeVakcine> stanjeVakcine;

    /**
     * Gets the value of the stanjeVakcine property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stanjeVakcine property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStanjeVakcine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StanjeVakcina.StanjeVakcine }
     * 
     * 
     */
    public List<StanjeVakcina.StanjeVakcine> getStanjeVakcine() {
        if (stanjeVakcine == null) {
            stanjeVakcine = new ArrayList<StanjeVakcina.StanjeVakcine>();
        }
        return this.stanjeVakcine;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="vakcina" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="dostupno" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlRootElement(name = "stanje_vakcine")
    @XmlType(name = "", propOrder = {
        "vakcina",
        "dostupno"
    })
    public static class StanjeVakcine {

        @XmlElement(required = true)
        protected String vakcina;
        @XmlElement(required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger dostupno;

        /**
         * Gets the value of the vakcina property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVakcina() {
            return vakcina;
        }

        /**
         * Sets the value of the vakcina property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVakcina(String value) {
            this.vakcina = value;
        }

        /**
         * Gets the value of the dostupno property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getDostupno() {
            return dostupno;
        }

        /**
         * Sets the value of the dostupno property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setDostupno(BigInteger value) {
            this.dostupno = value;
        }

    }

}
