//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.13 at 02:53:38 PM CET 
//


package vakcinac.io.civil.servant.models.sluz;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import vakcinac.io.core.annotations.RegisterExistEntity;
import vakcinac.io.core.annotations.RegisterXmlScheme;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="radnik" type="{https://www.vakcinac-io.rs/sluzbenik}Tsluzbenik"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "radnik"
})
@XmlRootElement(name = "sluzbenik")
@RegisterXmlScheme(
	schemePath="/data/schemes/sluzbenik.xsd",
	targetNamespace="https://www.vakcinac-io.rs/sluzbenik",
	shortNamespace="sluz"
)
@RegisterExistEntity(
	collectionUri="db/sluzbenici"
)
public class Sluzbenik {

    @XmlElement(required = true)
    protected Tsluzbenik radnik;

    /**
     * Gets the value of the radnik property.
     * 
     * @return
     *     possible object is
     *     {@link Tsluzbenik }
     *     
     */
    public Tsluzbenik getRadnik() {
        return radnik;
    }

    /**
     * Sets the value of the radnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tsluzbenik }
     *     
     */
    public void setRadnik(Tsluzbenik value) {
        this.radnik = value;
    }

}
