//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 10:51:42 PM CET 
//


package vakcinac.io.citizen.models.izv;

import java.math.BigInteger;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import vakcinac.io.core.annotations.RegisterExistEntity;
import vakcinac.io.core.annotations.RegisterXmlScheme;
import vakcinac.io.core.annotations.RegisterXslFo;
import vakcinac.io.core.annotations.RegisterXslt;
import vakcinac.io.citizen.models.os.Tlink;
import vakcinac.io.citizen.models.os.Tmeta;
import vakcinac.io.core.utils.adapters.LocalDateAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="link" type="{https://www.vakcinac-io.rs/osnovna-sema}Tlink" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="meta" type="{https://www.vakcinac-io.rs/osnovna-sema}Tmeta" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="statistika-zahteva">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="podneto" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                   &lt;element name="primljeno" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                   &lt;element name="izdato" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="statistika-doza">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ukupno-izdatih-doza" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                   &lt;element name="izdate-doze">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="doza" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>nonNegativeInteger">
 *                                     &lt;attribute name="redni-broj" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="statistika-proizvodjaca">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="proizvodjac" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="broj-doza" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{https://www.vakcinac-io.rs/osnovna-sema}rdfMainDocument"/>
 *       &lt;attribute name="izdato" use="required" type="{https://www.vakcinac-io.rs/osnovna-sema}TdateString" />
 *       &lt;attribute name="od" use="required" type="{https://www.vakcinac-io.rs/osnovna-sema}TdateString" />
 *       &lt;attribute name="do" use="required" type="{https://www.vakcinac-io.rs/osnovna-sema}TdateString" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "link",
    "meta",
    "statistikaZahteva",
    "statistikaDoza",
    "statistikaProizvodjaca"
})
@XmlRootElement(name = "izvestaj-o-imunizaciji")
@RegisterXmlScheme(
	schemePath="/data/schemes/izvestaj_o_imunizaciji.xsd",
	targetNamespace="https://www.vakcinac-io.rs/izvestaj",
	shortNamespace="izv"
)
@RegisterExistEntity(
	collectionUri="db/izvestaji"
)
@RegisterXslt(
	xslPath="/data/xslt/izvestaj_o_imunizaciji.xsl"
)
@RegisterXslFo(
	xslPath="/data/xsl-fo/izvestaj_o_imunizaciji.xsl"
)
public class IzvestajOImunizaciji {

    protected List<Tlink> link;
    protected List<Tmeta> meta;
    @XmlElement(name = "statistika-zahteva", required = true)
    protected IzvestajOImunizaciji.StatistikaZahteva statistikaZahteva;
    @XmlElement(name = "statistika-doza", required = true)
    protected IzvestajOImunizaciji.StatistikaDoza statistikaDoza;
    @XmlElement(name = "statistika-proizvodjaca", required = true)
    protected IzvestajOImunizaciji.StatistikaProizvodjaca statistikaProizvodjaca;
    @XmlAttribute(name = "izdato", required = true)
    @XmlJavaTypeAdapter(LocalDateAdapter.class)
    protected LocalDate izdato;
    @XmlAttribute(name = "od", required = true)
    @XmlJavaTypeAdapter(LocalDateAdapter.class)
    protected LocalDate od;
    @XmlAttribute(name = "do", required = true)
    @XmlJavaTypeAdapter(LocalDateAdapter.class)
    protected LocalDate _do;
    @XmlAttribute(name = "about")
    @XmlSchemaType(name = "anySimpleType")
    protected String about;
    @XmlAttribute(name = "typeof")
    @XmlSchemaType(name = "anySimpleType")
    protected String typeof;

    /**
     * Gets the value of the link property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the link property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tlink }
     * 
     * 
     */
    public List<Tlink> getLink() {
        if (link == null) {
            link = new ArrayList<Tlink>();
        }
        return this.link;
    }

    /**
     * Gets the value of the meta property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the meta property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeta().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tmeta }
     * 
     * 
     */
    public List<Tmeta> getMeta() {
        if (meta == null) {
            meta = new ArrayList<Tmeta>();
        }
        return this.meta;
    }

    /**
     * Gets the value of the statistikaZahteva property.
     * 
     * @return
     *     possible object is
     *     {@link IzvestajOImunizaciji.StatistikaZahteva }
     *     
     */
    public IzvestajOImunizaciji.StatistikaZahteva getStatistikaZahteva() {
        return statistikaZahteva;
    }

    /**
     * Sets the value of the statistikaZahteva property.
     * 
     * @param value
     *     allowed object is
     *     {@link IzvestajOImunizaciji.StatistikaZahteva }
     *     
     */
    public void setStatistikaZahteva(IzvestajOImunizaciji.StatistikaZahteva value) {
        this.statistikaZahteva = value;
    }

    /**
     * Gets the value of the statistikaDoza property.
     * 
     * @return
     *     possible object is
     *     {@link IzvestajOImunizaciji.StatistikaDoza }
     *     
     */
    public IzvestajOImunizaciji.StatistikaDoza getStatistikaDoza() {
        return statistikaDoza;
    }

    /**
     * Sets the value of the statistikaDoza property.
     * 
     * @param value
     *     allowed object is
     *     {@link IzvestajOImunizaciji.StatistikaDoza }
     *     
     */
    public void setStatistikaDoza(IzvestajOImunizaciji.StatistikaDoza value) {
        this.statistikaDoza = value;
    }

    /**
     * Gets the value of the statistikaProizvodjaca property.
     * 
     * @return
     *     possible object is
     *     {@link IzvestajOImunizaciji.StatistikaProizvodjaca }
     *     
     */
    public IzvestajOImunizaciji.StatistikaProizvodjaca getStatistikaProizvodjaca() {
        return statistikaProizvodjaca;
    }

    /**
     * Sets the value of the statistikaProizvodjaca property.
     * 
     * @param value
     *     allowed object is
     *     {@link IzvestajOImunizaciji.StatistikaProizvodjaca }
     *     
     */
    public void setStatistikaProizvodjaca(IzvestajOImunizaciji.StatistikaProizvodjaca value) {
        this.statistikaProizvodjaca = value;
    }

    /**
     * Gets the value of the izdato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public LocalDate getIzdato() {
        return izdato;
    }

    /**
     * Sets the value of the izdato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIzdato(LocalDate value) {
        this.izdato = value;
    }

    /**
     * Gets the value of the od property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public LocalDate getOd() {
        return od;
    }

    /**
     * Sets the value of the od property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOd(LocalDate value) {
        this.od = value;
    }

    /**
     * Gets the value of the do property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public LocalDate getDo() {
        return _do;
    }

    /**
     * Sets the value of the do property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDo(LocalDate value) {
        this._do = value;
    }

    /**
     * Gets the value of the about property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbout(String value) {
        this.about = value;
    }

    /**
     * Gets the value of the typeof property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeof() {
        return typeof;
    }

    /**
     * Sets the value of the typeof property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeof(String value) {
        this.typeof = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ukupno-izdatih-doza" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *         &lt;element name="izdate-doze">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="doza" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>nonNegativeInteger">
     *                           &lt;attribute name="redni-broj" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ukupnoIzdatihDoza",
        "izdateDoze"
    })
    public static class StatistikaDoza {

        @XmlElement(name = "ukupno-izdatih-doza", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger ukupnoIzdatihDoza;
        @XmlElement(name = "izdate-doze", required = true)
        protected IzvestajOImunizaciji.StatistikaDoza.IzdateDoze izdateDoze;

        /**
         * Gets the value of the ukupnoIzdatihDoza property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getUkupnoIzdatihDoza() {
            return ukupnoIzdatihDoza;
        }

        /**
         * Sets the value of the ukupnoIzdatihDoza property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setUkupnoIzdatihDoza(BigInteger value) {
            this.ukupnoIzdatihDoza = value;
        }

        /**
         * Gets the value of the izdateDoze property.
         * 
         * @return
         *     possible object is
         *     {@link IzvestajOImunizaciji.StatistikaDoza.IzdateDoze }
         *     
         */
        public IzvestajOImunizaciji.StatistikaDoza.IzdateDoze getIzdateDoze() {
            return izdateDoze;
        }

        /**
         * Sets the value of the izdateDoze property.
         * 
         * @param value
         *     allowed object is
         *     {@link IzvestajOImunizaciji.StatistikaDoza.IzdateDoze }
         *     
         */
        public void setIzdateDoze(IzvestajOImunizaciji.StatistikaDoza.IzdateDoze value) {
            this.izdateDoze = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="doza" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>nonNegativeInteger">
         *                 &lt;attribute name="redni-broj" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "doza"
        })
        public static class IzdateDoze {

            protected List<IzvestajOImunizaciji.StatistikaDoza.IzdateDoze.Doza> doza;

            /**
             * Gets the value of the doza property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the doza property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDoza().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link IzvestajOImunizaciji.StatistikaDoza.IzdateDoze.Doza }
             * 
             * 
             */
            public List<IzvestajOImunizaciji.StatistikaDoza.IzdateDoze.Doza> getDoza() {
                if (doza == null) {
                    doza = new ArrayList<IzvestajOImunizaciji.StatistikaDoza.IzdateDoze.Doza>();
                }
                return this.doza;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>nonNegativeInteger">
             *       &lt;attribute name="redni-broj" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Doza {

                @XmlValue
                @XmlSchemaType(name = "nonNegativeInteger")
                protected BigInteger value;
                @XmlAttribute(name = "redni-broj", required = true)
                @XmlSchemaType(name = "positiveInteger")
                protected BigInteger redniBroj;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setValue(BigInteger value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the redniBroj property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getRedniBroj() {
                    return redniBroj;
                }

                /**
                 * Sets the value of the redniBroj property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setRedniBroj(BigInteger value) {
                    this.redniBroj = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="proizvodjac" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="broj-doza" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "proizvodjac"
    })
    public static class StatistikaProizvodjaca {

        protected List<IzvestajOImunizaciji.StatistikaProizvodjaca.Proizvodjac> proizvodjac;

        /**
         * Gets the value of the proizvodjac property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the proizvodjac property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProizvodjac().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link IzvestajOImunizaciji.StatistikaProizvodjaca.Proizvodjac }
         * 
         * 
         */
        public List<IzvestajOImunizaciji.StatistikaProizvodjaca.Proizvodjac> getProizvodjac() {
            if (proizvodjac == null) {
                proizvodjac = new ArrayList<IzvestajOImunizaciji.StatistikaProizvodjaca.Proizvodjac>();
            }
            return this.proizvodjac;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="broj-doza" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "naziv",
            "brojDoza"
        })
        public static class Proizvodjac {

            @XmlElement(required = true)
            protected String naziv;
            @XmlElement(name = "broj-doza", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger brojDoza;

            /**
             * Gets the value of the naziv property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNaziv() {
                return naziv;
            }

            /**
             * Sets the value of the naziv property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNaziv(String value) {
                this.naziv = value;
            }

            /**
             * Gets the value of the brojDoza property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getBrojDoza() {
                return brojDoza;
            }

            /**
             * Sets the value of the brojDoza property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setBrojDoza(BigInteger value) {
                this.brojDoza = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="podneto" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *         &lt;element name="primljeno" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *         &lt;element name="izdato" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "podneto",
        "primljeno",
        "izdato"
    })
    public static class StatistikaZahteva {

        @XmlElement(required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger podneto;
        @XmlElement(required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger primljeno;
        @XmlElement(required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger izdato;

        /**
         * Gets the value of the podneto property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getPodneto() {
            return podneto;
        }

        /**
         * Sets the value of the podneto property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPodneto(BigInteger value) {
            this.podneto = value;
        }

        /**
         * Gets the value of the primljeno property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getPrimljeno() {
            return primljeno;
        }

        /**
         * Sets the value of the primljeno property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPrimljeno(BigInteger value) {
            this.primljeno = value;
        }

        /**
         * Gets the value of the izdato property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getIzdato() {
            return izdato;
        }

        /**
         * Sets the value of the izdato property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setIzdato(BigInteger value) {
            this.izdato = value;
        }

    }

}
