//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.07 at 03:25:01 PM CET 
//


package vakcinac.io.citizen.models.izv;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the vakcinac.io.citizen.models.izv package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: vakcinac.io.citizen.models.izv
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji }
     * 
     */
    public IzvestajOImunizaciji createIzvestajOImunizaciji() {
        return new IzvestajOImunizaciji();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji.StatistikaProizvodjaca }
     * 
     */
    public IzvestajOImunizaciji.StatistikaProizvodjaca createIzvestajOImunizacijiStatistikaProizvodjaca() {
        return new IzvestajOImunizaciji.StatistikaProizvodjaca();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji.StatistikaDoza }
     * 
     */
    public IzvestajOImunizaciji.StatistikaDoza createIzvestajOImunizacijiStatistikaDoza() {
        return new IzvestajOImunizaciji.StatistikaDoza();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji.StatistikaDoza.IzdateDoze }
     * 
     */
    public IzvestajOImunizaciji.StatistikaDoza.IzdateDoze createIzvestajOImunizacijiStatistikaDozaIzdateDoze() {
        return new IzvestajOImunizaciji.StatistikaDoza.IzdateDoze();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji.StatistikaZahteva }
     * 
     */
    public IzvestajOImunizaciji.StatistikaZahteva createIzvestajOImunizacijiStatistikaZahteva() {
        return new IzvestajOImunizaciji.StatistikaZahteva();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji.StatistikaProizvodjaca.Proizvodjac }
     * 
     */
    public IzvestajOImunizaciji.StatistikaProizvodjaca.Proizvodjac createIzvestajOImunizacijiStatistikaProizvodjacaProizvodjac() {
        return new IzvestajOImunizaciji.StatistikaProizvodjaca.Proizvodjac();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji.StatistikaDoza.IzdateDoze.Doza }
     * 
     */
    public IzvestajOImunizaciji.StatistikaDoza.IzdateDoze.Doza createIzvestajOImunizacijiStatistikaDozaIzdateDozeDoza() {
        return new IzvestajOImunizaciji.StatistikaDoza.IzdateDoze.Doza();
    }

}
