//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.13 at 03:24:44 PM CET 
//


package vakcinac.io.civil.servant.models.term;

import java.time.LocalDateTime;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import vakcinac.io.core.utils.adapters.LocalDateTimeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vreme" type="{https://www.vakcinac-io.rs/osnovna-sema}TdateTimeString"/>
 *         &lt;choice>
 *           &lt;element name="jmbg" type="{https://www.vakcinac-io.rs/osnovna-sema}Tjmbg"/>
 *           &lt;element name="broj-pasosa-ebs" type="{https://www.vakcinac-io.rs/osnovna-sema}Tpasos"/>
 *         &lt;/choice>
 *         &lt;element name="vakcina" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="realizovan" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vreme",
    "jmbg",
    "brojPasosaEbs",
    "vakcina",
    "realizovan"
})
@XmlRootElement(name = "termin")
public class Termin {

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(LocalDateTimeAdapter.class)
    protected LocalDateTime vreme;
    protected String jmbg;
    @XmlElement(name = "broj-pasosa-ebs")
    protected String brojPasosaEbs;
    @XmlElement(required = true)
    protected String vakcina;
    @XmlElement(required = true, type = Boolean.class, nillable = true)
    protected Boolean realizovan;

    /**
     * Gets the value of the vreme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public LocalDateTime getVreme() {
        return vreme;
    }

    /**
     * Sets the value of the vreme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVreme(LocalDateTime value) {
        this.vreme = value;
    }

    /**
     * Gets the value of the jmbg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJmbg() {
        return jmbg;
    }

    /**
     * Sets the value of the jmbg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJmbg(String value) {
        this.jmbg = value;
    }

    /**
     * Gets the value of the brojPasosaEbs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojPasosaEbs() {
        return brojPasosaEbs;
    }

    /**
     * Sets the value of the brojPasosaEbs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojPasosaEbs(String value) {
        this.brojPasosaEbs = value;
    }

    /**
     * Gets the value of the vakcina property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVakcina() {
        return vakcina;
    }

    /**
     * Sets the value of the vakcina property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVakcina(String value) {
        this.vakcina = value;
    }

    /**
     * Gets the value of the realizovan property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRealizovan() {
        return realizovan;
    }

    /**
     * Sets the value of the realizovan property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRealizovan(Boolean value) {
        this.realizovan = value;
    }

}
