//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 10:51:38 PM CET 
//


package vakcinac.io.citizen.models.dig;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the vakcinac.io.citizen.models.dig package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: vakcinac.io.citizen.models.dig
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DigitalniSertifikat }
     * 
     */
    public DigitalniSertifikat createDigitalniSertifikat() {
        return new DigitalniSertifikat();
    }

    /**
     * Create an instance of {@link DigitalniSertifikat.Testovi }
     * 
     */
    public DigitalniSertifikat.Testovi createDigitalniSertifikatTestovi() {
        return new DigitalniSertifikat.Testovi();
    }

    /**
     * Create an instance of {@link DigitalniSertifikat.Vakcinacije }
     * 
     */
    public DigitalniSertifikat.Vakcinacije createDigitalniSertifikatVakcinacije() {
        return new DigitalniSertifikat.Vakcinacije();
    }

    /**
     * Create an instance of {@link TnosilacSertifikata }
     * 
     */
    public TnosilacSertifikata createTnosilacSertifikata() {
        return new TnosilacSertifikata();
    }

    /**
     * Create an instance of {@link DigitalniSertifikat.Testovi.Test }
     * 
     */
    public DigitalniSertifikat.Testovi.Test createDigitalniSertifikatTestoviTest() {
        return new DigitalniSertifikat.Testovi.Test();
    }

    /**
     * Create an instance of {@link DigitalniSertifikat.Vakcinacije.Vakcinacija }
     * 
     */
    public DigitalniSertifikat.Vakcinacije.Vakcinacija createDigitalniSertifikatVakcinacijeVakcinacija() {
        return new DigitalniSertifikat.Vakcinacije.Vakcinacija();
    }

}
