//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 10:51:38 PM CET 
//


package vakcinac.io.citizen.models.dig;

import java.time.LocalDate;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import vakcinac.io.citizen.models.os.TosobaSaJmbg;
import vakcinac.io.core.utils.adapters.LocalDateAdapter;


/**
 * <p>Java class for TnosilacSertifikata complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TnosilacSertifikata">
 *   &lt;complexContent>
 *     &lt;extension base="{https://www.vakcinac-io.rs/osnovna-sema}TosobaSaJmbg">
 *       &lt;sequence>
 *         &lt;element name="pol" type="{https://www.vakcinac-io.rs/osnovna-sema}Tpol"/>
 *         &lt;element name="br-pasosa" type="{https://www.vakcinac-io.rs/osnovna-sema}Tpasos"/>
 *         &lt;element name="datum-rodjenja" type="{https://www.vakcinac-io.rs/osnovna-sema}TdateString"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TnosilacSertifikata", propOrder = {
    "pol",
    "brPasosa",
    "datumRodjenja"
})
public class TnosilacSertifikata
    extends TosobaSaJmbg
{

    protected int pol;
    @XmlElement(name = "br-pasosa", required = true)
    protected String brPasosa;
    @XmlElement(name = "datum-rodjenja", required = true, type = String.class)
    @XmlJavaTypeAdapter(LocalDateAdapter.class)
    protected LocalDate datumRodjenja;

    /**
     * Gets the value of the pol property.
     * 
     */
    public int getPol() {
        return pol;
    }

    /**
     * Sets the value of the pol property.
     * 
     */
    public void setPol(int value) {
        this.pol = value;
    }

    /**
     * Gets the value of the brPasosa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrPasosa() {
        return brPasosa;
    }

    /**
     * Sets the value of the brPasosa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrPasosa(String value) {
        this.brPasosa = value;
    }

    /**
     * Gets the value of the datumRodjenja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public LocalDate getDatumRodjenja() {
        return datumRodjenja;
    }

    /**
     * Sets the value of the datumRodjenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatumRodjenja(LocalDate value) {
        this.datumRodjenja = value;
    }

}
