//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.07 at 03:25:10 PM CET 
//


package vakcinac.io.citizen.models.izj;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import vakcinac.io.citizen.annotations.RegisterExistEntity;
import vakcinac.io.citizen.annotations.RegisterXmlScheme;
import vakcinac.io.citizen.annotations.RegisterXslt;
import vakcinac.io.citizen.models.os.Tkontakt;
import vakcinac.io.citizen.utils.adapters.LocalDateAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="podnosilac-izjave">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="podnosilac" type="{https://www.vakcinac-io.rs/interesovanje}Tpodnosilac"/>
 *                   &lt;element name="kontakt" type="{https://www.vakcinac-io.rs/osnovna-sema}Tkontakt"/>
 *                   &lt;element name="dobrovoljan-davalac-krvi" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="informacije-o-primanju-vakcine">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="opstina" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="proizvodjaci">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence maxOccurs="unbounded">
 *                             &lt;element name="proizvodjac" type="{https://www.vakcinac-io.rs/interesovanje}Tproizvodjac"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="dan" use="required" type="{https://www.vakcinac-io.rs/osnovna-sema}TdateString" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "podnosilacIzjave",
    "informacijeOPrimanjuVakcine"
})
@XmlRootElement(name = "izjava-interesovanja-za-vakcinisanje")
@RegisterXmlScheme(
	schemePath="/data/schemes/izjava_interesovanja_za_vakcinisanje.xsd",
	targetNamespace="https://www.vakcinac-io.rs/interesovanje",
	shortNamespace="izj"
)
@RegisterExistEntity(
	collectionUri="db/izjave-interesovanja"
)
@RegisterXslt(
	xslPath="/data/xslt/iskazivanje_interesovanja_za_vakcinisanje.xsl"
)
public class IzjavaInteresovanjaZaVakcinisanje {

    @XmlElement(name = "podnosilac-izjave", required = true)
    protected IzjavaInteresovanjaZaVakcinisanje.PodnosilacIzjave podnosilacIzjave;
    @XmlElement(name = "informacije-o-primanju-vakcine", required = true)
    protected IzjavaInteresovanjaZaVakcinisanje.InformacijeOPrimanjuVakcine informacijeOPrimanjuVakcine;
    @XmlAttribute(name = "dan", required = true)
    @XmlJavaTypeAdapter(LocalDateAdapter.class)
    protected LocalDate dan;

    /**
     * Gets the value of the podnosilacIzjave property.
     * 
     * @return
     *     possible object is
     *     {@link IzjavaInteresovanjaZaVakcinisanje.PodnosilacIzjave }
     *     
     */
    public IzjavaInteresovanjaZaVakcinisanje.PodnosilacIzjave getPodnosilacIzjave() {
        return podnosilacIzjave;
    }

    /**
     * Sets the value of the podnosilacIzjave property.
     * 
     * @param value
     *     allowed object is
     *     {@link IzjavaInteresovanjaZaVakcinisanje.PodnosilacIzjave }
     *     
     */
    public void setPodnosilacIzjave(IzjavaInteresovanjaZaVakcinisanje.PodnosilacIzjave value) {
        this.podnosilacIzjave = value;
    }

    /**
     * Gets the value of the informacijeOPrimanjuVakcine property.
     * 
     * @return
     *     possible object is
     *     {@link IzjavaInteresovanjaZaVakcinisanje.InformacijeOPrimanjuVakcine }
     *     
     */
    public IzjavaInteresovanjaZaVakcinisanje.InformacijeOPrimanjuVakcine getInformacijeOPrimanjuVakcine() {
        return informacijeOPrimanjuVakcine;
    }

    /**
     * Sets the value of the informacijeOPrimanjuVakcine property.
     * 
     * @param value
     *     allowed object is
     *     {@link IzjavaInteresovanjaZaVakcinisanje.InformacijeOPrimanjuVakcine }
     *     
     */
    public void setInformacijeOPrimanjuVakcine(IzjavaInteresovanjaZaVakcinisanje.InformacijeOPrimanjuVakcine value) {
        this.informacijeOPrimanjuVakcine = value;
    }

    /**
     * Gets the value of the dan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public LocalDate getDan() {
        return dan;
    }

    /**
     * Sets the value of the dan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDan(LocalDate value) {
        this.dan = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="opstina" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="proizvodjaci">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence maxOccurs="unbounded">
     *                   &lt;element name="proizvodjac" type="{https://www.vakcinac-io.rs/interesovanje}Tproizvodjac"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "opstina",
        "proizvodjaci"
    })
    public static class InformacijeOPrimanjuVakcine {

        @XmlElement(required = true)
        protected String opstina;
        @XmlElement(required = true)
        protected IzjavaInteresovanjaZaVakcinisanje.InformacijeOPrimanjuVakcine.Proizvodjaci proizvodjaci;

        /**
         * Gets the value of the opstina property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOpstina() {
            return opstina;
        }

        /**
         * Sets the value of the opstina property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOpstina(String value) {
            this.opstina = value;
        }

        /**
         * Gets the value of the proizvodjaci property.
         * 
         * @return
         *     possible object is
         *     {@link IzjavaInteresovanjaZaVakcinisanje.InformacijeOPrimanjuVakcine.Proizvodjaci }
         *     
         */
        public IzjavaInteresovanjaZaVakcinisanje.InformacijeOPrimanjuVakcine.Proizvodjaci getProizvodjaci() {
            return proizvodjaci;
        }

        /**
         * Sets the value of the proizvodjaci property.
         * 
         * @param value
         *     allowed object is
         *     {@link IzjavaInteresovanjaZaVakcinisanje.InformacijeOPrimanjuVakcine.Proizvodjaci }
         *     
         */
        public void setProizvodjaci(IzjavaInteresovanjaZaVakcinisanje.InformacijeOPrimanjuVakcine.Proizvodjaci value) {
            this.proizvodjaci = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence maxOccurs="unbounded">
         *         &lt;element name="proizvodjac" type="{https://www.vakcinac-io.rs/interesovanje}Tproizvodjac"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "proizvodjac"
        })
        public static class Proizvodjaci {

            @XmlElement(type = Integer.class)
            protected List<Integer> proizvodjac;

            /**
             * Gets the value of the proizvodjac property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the proizvodjac property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getProizvodjac().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Integer }
             * 
             * 
             */
            public List<Integer> getProizvodjac() {
                if (proizvodjac == null) {
                    proizvodjac = new ArrayList<Integer>();
                }
                return this.proizvodjac;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="podnosilac" type="{https://www.vakcinac-io.rs/interesovanje}Tpodnosilac"/>
     *         &lt;element name="kontakt" type="{https://www.vakcinac-io.rs/osnovna-sema}Tkontakt"/>
     *         &lt;element name="dobrovoljan-davalac-krvi" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "podnosilac",
        "kontakt",
        "dobrovoljanDavalacKrvi"
    })
    public static class PodnosilacIzjave {

        @XmlElement(required = true)
        protected Tpodnosilac podnosilac;
        @XmlElement(required = true)
        protected Tkontakt kontakt;
        @XmlElement(name = "dobrovoljan-davalac-krvi")
        protected boolean dobrovoljanDavalacKrvi;

        /**
         * Gets the value of the podnosilac property.
         * 
         * @return
         *     possible object is
         *     {@link Tpodnosilac }
         *     
         */
        public Tpodnosilac getPodnosilac() {
            return podnosilac;
        }

        /**
         * Sets the value of the podnosilac property.
         * 
         * @param value
         *     allowed object is
         *     {@link Tpodnosilac }
         *     
         */
        public void setPodnosilac(Tpodnosilac value) {
            this.podnosilac = value;
        }

        /**
         * Gets the value of the kontakt property.
         * 
         * @return
         *     possible object is
         *     {@link Tkontakt }
         *     
         */
        public Tkontakt getKontakt() {
            return kontakt;
        }

        /**
         * Sets the value of the kontakt property.
         * 
         * @param value
         *     allowed object is
         *     {@link Tkontakt }
         *     
         */
        public void setKontakt(Tkontakt value) {
            this.kontakt = value;
        }

        /**
         * Gets the value of the dobrovoljanDavalacKrvi property.
         * 
         */
        public boolean isDobrovoljanDavalacKrvi() {
            return dobrovoljanDavalacKrvi;
        }

        /**
         * Sets the value of the dobrovoljanDavalacKrvi property.
         * 
         */
        public void setDobrovoljanDavalacKrvi(boolean value) {
            this.dobrovoljanDavalacKrvi = value;
        }

    }

}
