//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 10:51:40 PM CET 
//


package vakcinac.io.citizen.models.izj;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import vakcinac.io.citizen.models.os.TosobaSaJmbg;


/**
 * <p>Java class for Tpodnosilac complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Tpodnosilac">
 *   &lt;complexContent>
 *     &lt;extension base="{https://www.vakcinac-io.rs/osnovna-sema}TosobaSaJmbg">
 *       &lt;sequence>
 *         &lt;element name="drzavljanstvo" type="{https://www.vakcinac-io.rs/interesovanje}Tdrzavljanstvo"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tpodnosilac", propOrder = {
    "drzavljanstvo"
})
public class Tpodnosilac
    extends TosobaSaJmbg
{

    protected int drzavljanstvo;

    /**
     * Gets the value of the drzavljanstvo property.
     * 
     */
    public int getDrzavljanstvo() {
        return drzavljanstvo;
    }

    /**
     * Sets the value of the drzavljanstvo property.
     * 
     */
    public void setDrzavljanstvo(int value) {
        this.drzavljanstvo = value;
    }

}
