//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.13 at 03:51:35 PM CET 
//


package vakcinac.io.civil.servant.models.red;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import vakcinac.io.core.annotations.RegisterExistEntity;
import vakcinac.io.core.annotations.RegisterXmlScheme;
import vakcinac.io.core.utils.adapters.LocalDateAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="gradjanin-u-redu">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="minimalno-vreme" type="{https://www.vakcinac-io.rs/osnovna-sema}TdateString"/>
 *                   &lt;element name="vakcine">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence maxOccurs="unbounded">
 *                             &lt;element name="vakcina" type="{https://www.vakcinac-io.rs/osnovna-sema}Tproizvodjac"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;choice>
 *                     &lt;element name="jmbg" type="{https://www.vakcinac-io.rs/osnovna-sema}Tjmbg"/>
 *                     &lt;element name="broj-pasosa-ebs" type="{https://www.vakcinac-io.rs/osnovna-sema}Tpasos"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gradjaninURedu"
})
@XmlRootElement(name = "red-cekanja")
@RegisterXmlScheme(
	schemePath="/data/schemes/red_cekanja.xsd",
	targetNamespace="https://www.vakcinac-io.rs/red-cekanja",
	shortNamespace="red"
)
@RegisterExistEntity(
	collectionUri="db/termini"
)
public class RedCekanja {

    @XmlElement(name = "gradjanin-u-redu")
    protected List<RedCekanja.GradjaninURedu> gradjaninURedu;

    /**
     * Gets the value of the gradjaninURedu property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gradjaninURedu property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGradjaninURedu().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RedCekanja.GradjaninURedu }
     * 
     * 
     */
    public List<RedCekanja.GradjaninURedu> getGradjaninURedu() {
        if (gradjaninURedu == null) {
            gradjaninURedu = new ArrayList<RedCekanja.GradjaninURedu>();
        }
        return this.gradjaninURedu;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="minimalno-vreme" type="{https://www.vakcinac-io.rs/osnovna-sema}TdateString"/>
     *         &lt;element name="vakcine">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence maxOccurs="unbounded">
     *                   &lt;element name="vakcina" type="{https://www.vakcinac-io.rs/osnovna-sema}Tproizvodjac"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;choice>
     *           &lt;element name="jmbg" type="{https://www.vakcinac-io.rs/osnovna-sema}Tjmbg"/>
     *           &lt;element name="broj-pasosa-ebs" type="{https://www.vakcinac-io.rs/osnovna-sema}Tpasos"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "minimalnoVreme",
        "vakcine",
        "jmbg",
        "brojPasosaEbs"
    })
    @XmlRootElement(name = "gradjanin-u-redu")
    public static class GradjaninURedu {

        @XmlElement(name = "minimalno-vreme", required = true, type = String.class)
        @XmlJavaTypeAdapter(LocalDateAdapter.class)
        protected LocalDate minimalnoVreme;
        @XmlElement(required = true)
        protected RedCekanja.GradjaninURedu.Vakcine vakcine;
        protected String jmbg;
        @XmlElement(name = "broj-pasosa-ebs")
        protected String brojPasosaEbs;

        /**
         * Gets the value of the minimalnoVreme property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public LocalDate getMinimalnoVreme() {
            return minimalnoVreme;
        }

        /**
         * Sets the value of the minimalnoVreme property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMinimalnoVreme(LocalDate value) {
            this.minimalnoVreme = value;
        }

        /**
         * Gets the value of the vakcine property.
         * 
         * @return
         *     possible object is
         *     {@link RedCekanja.GradjaninURedu.Vakcine }
         *     
         */
        public RedCekanja.GradjaninURedu.Vakcine getVakcine() {
            return vakcine;
        }

        /**
         * Sets the value of the vakcine property.
         * 
         * @param value
         *     allowed object is
         *     {@link RedCekanja.GradjaninURedu.Vakcine }
         *     
         */
        public void setVakcine(RedCekanja.GradjaninURedu.Vakcine value) {
            this.vakcine = value;
        }

        /**
         * Gets the value of the jmbg property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJmbg() {
            return jmbg;
        }

        /**
         * Sets the value of the jmbg property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJmbg(String value) {
            this.jmbg = value;
        }

        /**
         * Gets the value of the brojPasosaEbs property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBrojPasosaEbs() {
            return brojPasosaEbs;
        }

        /**
         * Sets the value of the brojPasosaEbs property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBrojPasosaEbs(String value) {
            this.brojPasosaEbs = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence maxOccurs="unbounded">
         *         &lt;element name="vakcina" type="{https://www.vakcinac-io.rs/osnovna-sema}Tproizvodjac"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "vakcina"
        })
        public static class Vakcine {

            @XmlElement(type = Integer.class)
            protected List<Integer> vakcina;

            /**
             * Gets the value of the vakcina property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the vakcina property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getVakcina().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Integer }
             * 
             * 
             */
            public List<Integer> getVakcina() {
                if (vakcina == null) {
                    vakcina = new ArrayList<Integer>();
                }
                return this.vakcina;
            }

        }

    }

}
