//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 10:51:40 PM CET 
//


package vakcinac.io.civil.servant.models.izj;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the vakcinac.io.citizen.models.izj package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: vakcinac.io.citizen.models.izj
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IzjavaInteresovanjaZaVakcinisanje }
     * 
     */
    public IzjavaInteresovanjaZaVakcinisanje createIzjavaInteresovanjaZaVakcinisanje() {
        return new IzjavaInteresovanjaZaVakcinisanje();
    }

    /**
     * Create an instance of {@link IzjavaInteresovanjaZaVakcinisanje.InformacijeOPrimanjuVakcine }
     * 
     */
    public IzjavaInteresovanjaZaVakcinisanje.InformacijeOPrimanjuVakcine createIzjavaInteresovanjaZaVakcinisanjeInformacijeOPrimanjuVakcine() {
        return new IzjavaInteresovanjaZaVakcinisanje.InformacijeOPrimanjuVakcine();
    }

    /**
     * Create an instance of {@link IzjavaInteresovanjaZaVakcinisanje.PodnosilacIzjave }
     * 
     */
    public IzjavaInteresovanjaZaVakcinisanje.PodnosilacIzjave createIzjavaInteresovanjaZaVakcinisanjePodnosilacIzjave() {
        return new IzjavaInteresovanjaZaVakcinisanje.PodnosilacIzjave();
    }

    /**
     * Create an instance of {@link Tpodnosilac }
     * 
     */
    public Tpodnosilac createTpodnosilac() {
        return new Tpodnosilac();
    }

    /**
     * Create an instance of {@link IzjavaInteresovanjaZaVakcinisanje.InformacijeOPrimanjuVakcine.Proizvodjaci }
     * 
     */
    public IzjavaInteresovanjaZaVakcinisanje.InformacijeOPrimanjuVakcine.Proizvodjaci createIzjavaInteresovanjaZaVakcinisanjeInformacijeOPrimanjuVakcineProizvodjaci() {
        return new IzjavaInteresovanjaZaVakcinisanje.InformacijeOPrimanjuVakcine.Proizvodjaci();
    }

}
